package me;

import org.junit.*;
import static org.junit.Assert.*;

public class GemsTest {

    public GemsTest() {}

    @Test
    public void numMovesTest() throws Exception {
        assertEquals(1, Gems.numMoves(new String[]{"ABC", "ABC", "BAD"}));
        assertEquals(3, Gems.numMoves(new String[]{"ABB", "BAA", "ABB"}));
        assertEquals(4, Gems.numMoves(new String[]{"ABA", "BAB", "ABA"}));
        assertEquals(0, Gems.numMoves(new String[]{"ABC", "DEF", "GHI"}));
        assertEquals(4704, Gems.numMoves(new String[]{"ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA", "ABABABABABABABABABABABABABABABABABABABABABABABABAB", "BABABABABABABABABABABABABABABABABABABABABABABABABA"}));
        assertEquals(4, Gems.numMoves(new String[]{"JGBBDTGRERJIJRGATPHTJA", "FHGAQQAERQYDQGEEJEDCFF", "EHQYJCPTQFDIYYAHDPETPI", "HCPJDFTEJECCRJAJPBPEDQ"}));
        assertEquals(57, Gems.numMoves(new String[]{"QKGQHGUVFKGJVUJQVHV", "FXQGXUVKQJKKVFJXJFU", "GXGXUVGXUQHUQXQGHVH", "UFVGHKQHVFKFVUQJKKQ", "QHXHJVJXVXKUHJJXJJF", "HGFJJUXKJKGHFXVVKKF", "VJUXQJUQFHFUVKFUHJH", "UVUKGJJUJQHQKXGJQKX", "XUVVXKHKFVHXJHJGUKF", "JHFFJQJVGGFQVVQFQGV", "UKJJQXUJUUKQJJHQHQJ", "JXQXGHVVXHHVHHGKJXQ", "UJJGHFKUGUVQQJJVVKF", "HGQQXVUGGXXHKKVFKGQ", "JHUQJVUKUFGKQUXVUUK", "XFQXHUQVHUKHKXQHJKU", "HGJVJGXVJXXKHHXFGHK", "XQHHGGXJGQQVKFKFUQG", "UQHJGVGQVFJVUKQXQXX", "GGQHXKXQFUFFVXFVUUQ"}));  }

}


// {"JGBBDTGRERJIJRGATPHTJA"
//  "FHGAQQAERQYDQGEEJEDCFF"
//  "EHQYJCPTQFDIYYAHDPETPI"
//  "HCPJDFTEJECCRJAJPBPEDQ"}
